### ISSUE TITLE
Acces to database

### ISSUE THREAD

**Issue by quentin67100** [VCCRI/Spliceogen#2]
Hello,

I'm sorry to open an issue for that but i send you multiples mail without answer (probably go to spam). 
I'm very interested by your pre computed database. Where i Can download it ?

Thanks in advance

**Comment by smonger** [comment]
Hi Quentin,

I'm sorry, I can see your emails, they did go to spam. I'm replying to them now.

Thanks

**Comment by Iris-1025** [comment]
Hello,

I have the same request and sent an email 12 hours ago.
I look forward to receiving your reply.

Thank you very much!
